### ISSUE TITLE
Creer le formulaire d'inscription 

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/Branch#1]
Créer le formulaire d'inscription en s'inspirant de ce modèle : https://airtable.com/shrKJ1tiVe1M5zEFY
- [ ] Mettre en place le formulaire en respectant le type de chaque champ de saisis
- [ ] Mettre en place le minimum de CSS nécessaire
- [ ] Vérifier qu'il n'y a pas d'erreur linters

**Comment by Baroka-wp** [comment]
Bonjour @Gado229, 
C'est vous qui avez l'honneur de réaliser cette tâche. Ce n'est pas très compliqué. Je vais vous joindre à @choumanhussein . J'espère un résultat le **samedi 23 avril 2022 à 17 h**. Si la tâche n'est pas accomplie dans ce délai, elle sera attribuer à une autre équipe.

D'Abord, il faut tirer la branche de votre côté. Ensuite tu bascules sur la branche **milestone_1**. Dès que vous avez fini de travailler, tu pousses et tu ouvres un nouveau **pull request**

[POUR RAPPEL]
```
//pour cloner le dossier
git clone https://github.com/Baroka-wp/Branch

// basculer sur la brache
git checkout milestone_1

// Pour pousser
git add .
git commit -m " Un message court qui decrit ce que tu as fait. Veuilles toujours commencer ta phrase par une majuscule"
git push -u origin milestone_1

```
Happy coding 🍷 
---
_N'hésitez pas me contacter pour avoir une information supplémentaire. _
<img src="https://media2.giphy.com/media/toz7qXlLyHy9n8KfKO/giphy.gif"/>

**Comment by Baroka-wp** [comment]
Vous pouvez écrire ici vos commentaires ou poser vos questions

**Comment by choumanhussein** [comment]
Je viens de push ce que jai eu a faire..
Jai cloner le repertoire quand jai finis de travailler, je me suis alors rendu compte qu'il yavais les fichiers html,css mais vierge..
Je n'y ai pas toucher, jai juste coller mes fichiers et jai push tel..
En attendant votre feedback, je vous remercier coach de me permettre de participer..
Merci !!

**Comment by Baroka-wp** [comment]
@choumanhussein @Gado229 
Merci pour le travail acharné. On a réussi à tenir dans les temps. Je vais fermer cette tache. 

Félicitation a tous !
