### ISSUE TITLE
Faire évoluer la présentation de l'application

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/Branch#10]
- Se base sur ce modèle Figma pour designer l'application. https://www.figma.com/file/lsbI0f8998S3JSZtrB9HlP/Untitled?node-id=1%3A3158

**Comment by Baroka-wp** [comment]
Bonjour @choumanhussein & @Gado229, Merci pour votre travail acharné. Pour faire avance la présentation de l'application, veuillez vous baser sur ce modèle Figma.
1- Basculer sur la branche main 
``` git checkout main ```
2- Mettre a jour la branche main
``` git pull origin main```
3- Créer une nouvelle branche à partir de la branche main
``` git checkout -b milestone4```
4- aller sur ce lien pour trouver le modèle Figma : 
https://www.figma.com/file/lsbI0f8998S3JSZtrB9HlP/Untitled?node-id=1%3A3158
5- Faites de votre mieux que le résultat final ressemble au modèle. Respecter la police, les couleurs et les icônes 
6- Utiliser [Font Awesome](https://fontawesome.com/) pour les icônes

Bon travail !
<img src="https://media3.giphy.com/media/YM8lgxyaSuTLfTRfqH/giphy.gif"/>

**Comment by choumanhussein** [comment]
Je viens de creer la branch milestone4 et pousse mon travail..
Vous pouvez svp jettez un coup d'oeil et me donner votre feedback ?
Merci !!
