### ISSUE TITLE
Sauvegarder les données du formulaire au format JSON

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/Branch#2]
En utilisant JavaScript, sauvegarder les données du formulaire au format JSON sur un service en ligne (AWS/ MongoDB/ Firebase...)
- [x] Décider du meilleur service à utiliser
- [x] prendre en main l'API
- [x] Implémenter la fonctionnalité

**Comment by Baroka-wp** [comment]
Salut @AngeMervane1Jdev ,

C'est vous qui avez l'honneur de réaliser cette tâche. Je vais travailler avec vous sur la tâche. J'espère un résultat le **samedi 29 avril 2022 à 17 h**. Si la tâche n'est pas accomplie dans ce délai, elle sera attribuer à une autre équipe.

D'Abord, il faut tirer la branche de votre côté. Ensuite tu bascules sur une nouvelle branche **milestone_2 (par exemple)**. Dès que vous avez fini de travailler, tu pousses et tu ouvres un nouveau **pull request**

[POUR RAPPEL]
```
//pour cloner le dossier
git clone https://github.com/Baroka-wp/Branch

// basculer sur la brache
git checkout milestone_2

// Pour pousser
git add .
git commit -m " Un message court qui decrit ce que tu as fait. Veuilles toujours commencer ta phrase par une majuscule"
git push -u origin milestone_2

```
Happy coding 🍷 
---
_N'hésitez pas me contacter pour avoir une information supplémentaire. _
<img src="https://media2.giphy.com/media/toz7qXlLyHy9n8KfKO/giphy.gif"/>

**Comment by AngeMervane1Jdev** [comment]
Merci pour la tâche assignée. Maintenant j'ai plus de raisons pour comprendre encore plus ces services cloud que j'ai eu utilisé. 
Aws 
Firebase
Mongodb

**Comment by Baroka-wp** [comment]
@AngeMervane1Jdev Il faut souvent me taguer sur message si vous avez besoin de réponse.
Pour les tâches, ce que je veux qu'on fasse, c'est de voir comment stocker les informations avec JS sans être obligé d'utiliser une BD embarquée. Si vous avez une idée sur comment le faire autrement qu'en utilisant l'un de ces services que j'ai proposés, n'hésitez pas.

Le formulaire va ressembler à ceci simplement : https://airtable.com/shrKJ1tiVe1M5zEFY

**Comment by AngeMervane1Jdev** [comment]
@Baroka-wp Merci monsieur.
Non je n'ai pas d'autres propositions. Peut être dans mes recherches je vais trouver des choses encore interressanemtes.
