### ISSUE TITLE
Fonctionnalité d'envoie de mails [Milestone 5]

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/Branch#5]
- [ ] Créer une fonction pour envoyer un email aux inscrits. 
- [ ] Utiliser un faux text pour le draf du Email

**Comment by Baroka-wp** [comment]
Bonjour @AngeMervane1Jdev, Merci pour ton travail acharné. Pour faire avancer le projet, on va implémenter la fonction d'envoi de mail aux inscrits
1- Basculer sur la branche main 
``` git checkout main ```
2- Mettre a jour la branche main
``` git pull origin main```
3- Créer une nouvelle branche à partir de la branche main
``` git checkout -b milestone5```
4- Implémenter la fonction (On peut utiliser le SMTP de Google ou un autre service de messagerie si tu en connais)

Bon travail !
<img src="https://media3.giphy.com/media/toz7qXlLyHy9n8KfKO/giphy.gif"/>

**Comment by AngeMervane1Jdev** [comment]
@Baroka-wp  j'ai fais un push veuillez corriger
