### ISSUE TITLE
Récupérer les données stockées sur MongoDB 

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/Branch#8]
Récupérer les données stockées sur MongoDB pour les afficher dans un tableau.

**Comment by Baroka-wp** [comment]
@AngeMervane1Jdev et @choumanhussein , vous êtes assigné à cette tâche. Il s'agit de recuperer les données stockés sur MangoDb pour les afficher dans un tableau.

1-/  Revenir sur la branche principale `main`
`git checkout main`

2-/ Mettre a jour votre répertoire local
`git pull origin main`

3-/ crerer une nouvelle branche
`git checkout -b milestone3`

4-/ Créer un fichier `dasboard.html` pour y créer le tableau

5-/ ajouter la route vers ce nouveau fichier dans le `server.js`

6-/ Le tableau doit afficher au moins le `nom et prenom`, `email`, `sexe`, `age`. 

7-/ Vous pouvez utiliser bootstrap pour styliser le tableau rapidement

Happy coding, cheers 
<img src="https://media2.giphy.com/media/xT9DPpgeg64kyBSGFa/giphy.gif"/>

**Comment by AngeMervaneJdev** [comment]
@Baroka-wp  J'ai finis l'implementation, je laisserai @choumanhussein  resoudre les erreurs de linters si ça le dérange pas

**Comment by choumanhussein** [comment]
Daccord, Ca marche, merci pour ton travail !
Je gere ca ce soir !

**Comment by AngeMervaneJdev** [comment]
@Baroka-wp  on peut fermer l'issue non?
